-- Auto-generated by scripts/generate-seed-sql.ts
INSERT INTO cars (id, year, make, model, slug) VALUES
  (1, 1989, 'Nissan', 'Skyline GT-R R32', 'nissan-skyline-gtr-r32-1989'),
  (2, 1995, 'Nissan', 'Skyline GT-R R33', 'nissan-skyline-gtr-r33-1995'),
  (3, 1999, 'Nissan', 'Skyline GT-R R34', 'nissan-skyline-gtr-r34-1999'),
  (4, 1993, 'Nissan', '240SX S13', 'nissan-240sx-s13-1993'),
  (5, 1998, 'Nissan', 'Silvia S15 Spec-R', 'nissan-silvia-s15-1998'),
  (6, 1986, 'Toyota', 'Sprinter Trueno AE86', 'toyota-sprinter-trueno-ae86-1986'),
  (7, 1994, 'Toyota', 'Supra MK4', 'toyota-supra-mk4-1994'),
  (8, 1999, 'Toyota', 'Chaser JZX100', 'toyota-chaser-jzx100-1999'),
  (9, 1992, 'Mazda', 'RX-7 FD3S', 'mazda-rx7-fd3s-1992'),
  (10, 1989, 'Mazda', 'MX-5 Miata NA', 'mazda-mx5-miata-na-1989'),
  (11, 1999, 'Honda', 'S2000 AP1', 'honda-s2000-ap1-1999'),
  (12, 1997, 'Honda', 'Civic Type R EK9', 'honda-civic-type-r-ek9-1997'),
  (13, 2002, 'Honda', 'NSX-R', 'honda-nsx-r-2002'),
  (14, 2008, 'Mitsubishi', 'Lancer Evolution X', 'mitsubishi-evo-x-2008'),
  (15, 1999, 'Mitsubishi', 'Lancer Evolution VI', 'mitsubishi-evo-vi-1999'),
  (16, 2004, 'Subaru', 'Impreza WRX STI', 'subaru-impreza-wrx-sti-2004');

INSERT INTO tracks (id, name, slug, surface, length_km, region) VALUES
  (1, 'Mt. Akina Downhill', 'mt-akina-downhill', 'asphalt', 5.2, 'Touge'),
  (2, 'Hakone Pass', 'hakone-pass', 'asphalt', 6.8, 'Touge'),
  (3, 'Irohazaka', 'irohazaka', 'asphalt', 4.4, 'Touge'),
  (4, 'Mt. Fuji Touge', 'mt-fuji-touge', 'asphalt', 7.1, 'Touge'),
  (5, 'Tsukuba Circuit', 'tsukuba-circuit', 'asphalt', 2, 'Circuit'),
  (6, 'Fuji Speedway', 'fuji-speedway', 'asphalt', 4.5, 'Circuit'),
  (7, 'Suzuka Circuit', 'suzuka-circuit', 'asphalt', 5.8, 'Circuit'),
  (8, 'Bayshore Route', 'bayshore-route', 'asphalt', 12, 'Highway'),
  (9, 'Mt. Aso Dirt', 'mt-aso-dirt', 'dirt', 4.2, 'Off-road'),
  (10, 'Hokkaido Snow Run', 'hokkaido-snow-run', 'snow', 6.3, 'Off-road');
