import { carsSeed } from '../src/data/cars-seed';
import { tracksSeed } from '../src/data/tracks-seed';
import { writeFileSync, mkdirSync } from 'node:fs';

const escape = (s: string) => s.replace(/'/g, "''");

const carInserts = carsSeed
  .map((c, i) => `(${i + 1}, ${c.year}, '${escape(c.make)}', '${escape(c.model)}', '${escape(c.slug)}')`)
  .join(',\n  ');

const trackInserts = tracksSeed
  .map((t, i) => `(${i + 1}, '${escape(t.name)}', '${escape(t.slug)}', '${t.surface}', ${t.length_km ?? 'NULL'}, ${t.region ? `'${escape(t.region)}'` : 'NULL'})`)
  .join(',\n  ');

const sql = `-- Auto-generated by scripts/generate-seed-sql.ts
INSERT INTO cars (id, year, make, model, slug) VALUES
  ${carInserts};

INSERT INTO tracks (id, name, slug, surface, length_km, region) VALUES
  ${trackInserts};
`;

mkdirSync('migrations', { recursive: true });
writeFileSync('migrations/0002_seed_cars_tracks.sql', sql);
console.log('Wrote migrations/0002_seed_cars_tracks.sql');
